global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gitlab'
    static_configs:
      - targets: ['gitlab.com:443']

  - job_name: 'gitlab-ci-pipelines-exporter'
    static_configs:
      - targets: ['gitlab-ci-pipelines-exporter:8080']
